// <auto-generated />
namespace TaskManagmentSystem_TMS_.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class inti : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(inti));
        
        string IMigrationMetadata.Id
        {
            get { return "202401311805294_inti"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
